Repository etherchina/solidity-doc-cn, pull requests merged in 2018-03, with the labels that each got.

#8 完成"智能合约的简介"翻译，求review
  glossaries.md
  introduction-to-smart-contracts.rst
Labels: translate

#36 PR for issue#16 Contributing Chapter
  contributing.rst
Labels: reviewing

#32 installing-solidity.rst 求review git hash: 3594f02d51aac4a99d3f1fefbd37fa27346b75ae
  installing-solidity.rst
Labels: translate

#39 frequently-asked-questions 翻译完成，提交审核。
  frequently-asked-questions.rst
Labels: reviewing

#35 Complete the translation of abi-spec.rst
  .gitignore
  abi-spec.rst
Labels: 翻译中

#50 翻译 solidity-by-example.rst, git hash: 66ee9aa2f1d5af5dbabd6699e98935261d49558c
  solidity-by-example.rst
Labels: 审校中

#33 合约代码结构 初稿
  structure-of-a-contract.rst
Labels: 审校中
